spring:
  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://localhost:8888}
  application:
    name:
      user-service

application:
  config:
    library-url: ${LIBRARY_URL:http://localhost:8222/api/v1/library}

jwt:
  secret: ${JWT_SECRET:}
